// Builds quran-data.js from the alquran.cloud Uthmani edition.
// Usage: node scripts/build-data.mjs   (downloads to /tmp/quran.json if missing)
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';

const SRC = '/tmp/quran.json';
const OUT = new URL('../quran-data.js', import.meta.url);

if (!existsSync(SRC)) {
  console.log('downloading quran-uthmani…');
  execSync('curl -s -o ' + SRC + ' "https://api.alquran.cloud/v1/quran/quran-uthmani"', { stdio: 'inherit' });
}

const raw = JSON.parse(await (await import('node:fs/promises')).readFile(SRC, 'utf8'));
const surahs = raw.data.surahs;
if (surahs.length !== 114) throw new Error('expected 114 surahs, got ' + surahs.length);

// the API wraps every surah (except 9) with this exact basmala prefix on ayah 1
const BASMALA_STR = surahs[0].ayahs[0].text.replace(/^\uFEFF/, '');

// matching normalization used by the app's search box
function normalize(s) {
  return (s || '')
    .replace(/[أإآٱ]/g, 'ا')
    .replace(/ى/g, 'ي')
    .replace(/ة/g, 'ه')
    .replace(/[٠-٩]/g, (d) => '٠١٢٣٤٥٦٧٨٩'.indexOf(d))
    .replace(/[\u0640\u064B-\u0652\u0653\u0654\u0670\u06D6-\u06ED]/g, '')
    .replace(/سور[هة]\s*/gi, '')
    .trim();
}

function stripDiacritics(s) {
  return s
    .replace(/[أإآٱ]/g, 'ا') // keep display names tidy (alef waslah -> alef)
    .replace(/\u0640/g, '')
    .replace(/[\u064B-\u0652\u0653\u0654\u0670\u06D6-\u06ED]/g, '')
    .trim();
}

const toArNum = (n) => String(n).replace(/[0-9]/g, (d) => '٠١٢٣٤٥٦٧٨٩'[+d]);

const data = surahs.map((s) => {
  const rawName = s.name.replace(/^\s*سُورَةُ\s*/, '').trim();
  const answerArabicName = stripDiacritics(rawName);
  const ayahs = s.ayahs.map((a) => a.text.replace(/^\uFEFF/, ''));
  const v = [...ayahs];

  // split the baked-in basmala out of ayah 1 so it renders as the familiar
  // unnumbered line above the surah (surah 1 keeps it as its real ayah 1,
  // surah 9 never has one, surah 27 keeps the one inside verse 30 untouched).
  if (s.number !== 1 && v[0].startsWith(BASMALA_STR)) {
    v[0] = v[0].slice(BASMALA_STR.length).replace(/^\s+/, '');
  }

  return {
    n: s.number,
    an: answerArabicName,            // for display, e.g. 'الفاتحة'
    anTxt: toArNum(s.number),        // arabic-indic number for list/symbols
    search: normalize(answerArabicName),
    en: (s.englishName || '').toLowerCase(),
    count: s.ayahs.length,
    bsl: s.number !== 1 && s.number !== 9, // show the basmala line above ayah 1
    v,
  };
});

// sanity checks
const s1 = data[0], s9 = data[8], s2 = data[1];
if (s1.v[0].includes('الفاتحة')) throw new Error('bad surah1');
if (s1.v[0] !== BASMALA_STR) throw new Error('surah1 basmala expected as ayah1');
if (s2.v[0] !== 'الٓمٓ') throw new Error('surah2 ayah1 should be basmala-stripped -> الم: ' + JSON.stringify(s2.v[0]));
if (s9.v[0].startsWith(BASMALA_STR) || !s9.v[0].startsWith('بَر')) throw new Error('surah9 ayah1 should have no basmala');

const sizes = data.reduce((t, s) => t + s.v.join('').length, 0);
console.log(`built ${data.length} surahs, ${data.reduce((t, s) => t + s.count, 0)} ayahs, ~${(sizes / 1e6).toFixed(2)} MB of Arabic text`);

const js = '// auto-generated by scripts/build-data.mjs — do not edit by hand\n' +
  'window.QURAN_DATA = ' + JSON.stringify(data) + ';\n';
writeFileSync(OUT, js);
console.log('wrote ' + OUT.pathname.split('/').pop() + ' (' + (js.length / 1e6).toFixed(2) + ' MB)');